---
ID: "995bae9d-fc8a-4bef-9d58-4c9f0df1dccc"
Parent: "0c24a4c6-fc21-4acb-9186-27b6c0066f63"
Template: "0c24a4c6-fc21-4acb-9186-27b6c0066f63"
Path: /sitecore/templates/Feature/RichText/RichText/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180124T152306Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "60ff1b4c-268d-4faa-9f8c-6b247267a1c1"
      Hint: Header
      Value: $name
